version: '3.5'

services:

  kudos.api:
    image: kudosapi
    container_name: kudosapi  
    build:
      context: ./src/Kudos.Api/
      dockerfile: Dockerfile
    ports: 
      - "9001:80"
      - "9002:443"
    depends_on: 
    - "postgresql_database"
    environment:
        DockerCommandsConnectionString: "host=postgresql_database; username=postgres; Password=admin; Server=postgres; Database=DB; port=5432;"

  postgresql_database:
    restart: always 
    image: postgres:15.1-alpine3.17
    container_name: 'postgres'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

    volumes:
      - ./database-data:/var/lib/postgresql/data/
     
volumes:
  database-data: